export const APPLICATION_IPC_CHANNELS = [
  "application:get-shell-state",
  "application:list-commands",
  "application:execute-command",
  "application:project:choose-open-directory",
  "application:project:choose-create-directory",
  "application:project:open",
  "application:project:read-directory",
  "application:file:read-text",
  "application:file:write-text",
  "application:project:create",
  "application:project:list-chapters",
  "application:project:create-chapter",
  "application:project:rename-chapter",
  "application:project:duplicate-chapter",
  "application:project:delete-chapter",
  "application:project:select-chapter",
  "application:project:preview-recovery-draft",
  "application:project:apply-recovery-draft",
  "application:project:discard-recovery-draft",
  "application:search:rebuild-index",
  "application:search:query",
  "application:ai:generate-chapter-suggestion",
  "application:ai:start-chapter-suggestion-stream",
  "application:ai:next-chapter-suggestion-stream",
  "application:ai:cancel-chapter-suggestion-stream",
  "application:ai:start-chapter-suggestion-push-stream",
  "application:ai:cancel-chapter-suggestion-push-stream",
  "application:ai:generate-selection-preview",
  "application:ai:apply-selection-preview",
  "application:ai:apply-chapter-suggestion",
  "application:ai:list-workflow-runs",
  "application:ai:read-workflow-run",
  "application:agent-run:prepare-start",
  "application:agent-run:read-run-draft",
  "application:agent-run:update-run-draft",
  "application:agent-run:update-context-draft",
  "application:agent-run:refresh-context-draft",
  "application:agent-run:preview-context-budget",
  "application:agent-run:compact-context",
  "application:agent-run:start",
  "application:agent-run:stop",
  "application:agent-run:answer-user-input",
  "application:agent-run:resume",
  "application:agent-run:retry-step",
  "application:agent-run:retry-target",
  "application:agent-run:decide-plan",
  "application:agent-run:read-permission-summary",
  "application:agent-run:decide-plan-revision",
  "application:agent-run:refresh-context",
  "application:agent-run:decide-change-set",
  "application:agent-run:undo",
  "application:agent-run:read",
  "application:agent-run:list",
  "application:agent-conversation:create",
  "application:agent-conversation:list",
  "application:agent-conversation:read",
  "application:agent-conversation:archive",
  "application:agent-conversation:restore",
  "application:agent-conversation:search",
  "application:chapter:load",
  "application:chapter:edit",
  "application:chapter:save",
  "application:chapter:list-versions",
  "application:chapter:preview-version",
  "application:chapter:restore-version",
  "application:chapter:preview-suggestion-diff",
  "application:settings:list-model-profiles",
  "application:settings:discover-models",
  "application:settings:save-model-profile",
  "application:settings:save-model-secret",
  "application:settings:test-model-profile",
  "application:settings:list-agent-usage",
  "application:settings:clear-agent-usage",
  "application:plugins:load-registry",
  "application:plugins:set-enabled",
  "application:story-bible:load",
  "application:story-bible:save-asset",
  "application:story-bible:save-memory",
  "application:story-bible:build-consistency-report",
  "application:story-bible:build-context-candidates",
  "application:studio:load-config-asset",
  "application:studio:save-config-asset",
  "application:studio:restore-config-version",
  "application:preferences:load",
  "application:preferences:save"
] as const;

export type ApplicationIpcChannel = (typeof APPLICATION_IPC_CHANNELS)[number];

export const APPLICATION_IPC_EVENT_CHANNELS = [
  "application:ai:chapter-suggestion-push-event",
  "application:agent-run:event"
] as const;

export type ApplicationIpcEventChannel = (typeof APPLICATION_IPC_EVENT_CHANNELS)[number];

export function isApplicationIpcChannel(channel: string): channel is ApplicationIpcChannel {
  return APPLICATION_IPC_CHANNELS.includes(channel as ApplicationIpcChannel);
}
